name: Lint code style issues

on:
  pull_request:

jobs:
  lint-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: fileinfo, exif, gd, pdo, sqlite, pdo_sqlite, intl

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@v2
        with:
          testMode: true
          verboseMode: true
          pintVersion: 1.16.0

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci && composer install

      - name: Check formatting with Prettier
        run: npm run prettier:check