name: Docs

on:
  push:
    branches:
      - 1.x
    paths:
      - 'docs/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-docs:
    name: 'Update docs'
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@b0fbd1a7486a4776d7eb35e1a088bce4b6a6352f # v1.0.4
        with:
          trigger_url: ${{ secrets.DOCS_TRIGGER_URL }}