name: Pint (Fix)

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  fix-php-code-styling:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'duncanmcclean'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Pint Fix
        uses: aglipanci/laravel-pint-action@1.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
